version: '3'

services:

  mariadb:
    image: 'mariadb:latest'
    restart: 'always'
    env_file:
      - './mariadb.env'
    volumes:
      - './database:/var/lib/mysql'  
    ports:
      - "3306:3306"
    environment:
            MYSQL_DATABASE: mariadb
            MYSQL_USER: user
            MYSQL_PASSWORD: xyz1234567890
            MYSQL_ROOT_PASSWORD: xyz1234567890

   wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: xyz1234567890
      WORDPRESS_DB_NAME: xyz1234567890
    volumes:
      - wordpress:/var/www/html

