version: '3'

services:

  mariadb:
    image: 'mariadb:10.3'
    restart: 'always'
    env_file:
      - './mariadb.env'
    volumes:
      - './database:/var/lib/mysql'  
    ports:
      - "3306:3306"
    environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: xyz1234567890
            MYSQL_ROOT_PASSWORD: xyz1234567890

  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: xyz1234567890
            MYSQL_ROOT_PASSWORD: xyz1234567890
  
  php:
    image: 'caligari/wordpress-lamp:7.2'
    build: './'
    restart: 'always'
    env_file:
      - './php.env'
    volumes:
      - './www:/var/www/html'

